INSERT INTO CASHIER_USER (NAME, ID) VALUES ('MARTINA', 1);

INSERT INTO CASH_BALANCE (ID, AMOUNT,  CURRENCY,
 Denomination10,
 Denomination20,
 Denomination50,
CASHIER_USER_ID)
VALUES
(1, 1000, 'BGN',50, 0 , 10, 1);

INSERT INTO CASH_BALANCE (ID, AMOUNT,  CURRENCY,
 Denomination10,
 Denomination20,
 Denomination50,
CASHIER_USER_ID)
VALUES
(2, 2000, 'EUR', 100, 0 , 20, 1);

INSERT INTO CASH_OPERATION (ID, AMOUNT,  CURRENCY,
 Denomination10,
 Denomination20,
 Denomination50,
OPERATION, CASH_BALANCE_ID)
VALUES
(1, 1000, 'BGN',50, 0 , 10, 'DEPOSIT', 1);

INSERT INTO CASH_OPERATION (ID, AMOUNT,  CURRENCY,
 Denomination10,
 Denomination20,
 Denomination50,
OPERATION, CASH_BALANCE_ID)
VALUES
(2, 2000, 'EUR', 100, 0 , 20, 'DEPOSIT',   2);